run:
  timeout: 5m
  tests: true
  build-tags:
    - linux

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - dupl
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - dogsled
    - errname
    - errorlint
    - exportloopref
    - gochecknoinits
    - goprintffuncname
    - gosec
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tparallel
    - wastedassign
    - whitespace

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/mascli/troncli
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - ifElseChain
      - octalLiteral

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
