version: 2
project_name: troncli

builds:
  - main: ./cmd/troncli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - formats: 
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: https://github.com/mascli/troncli
    maintainer: "TronCLI Maintainers <maintainers@troncli.com>"
    description: "TronCLI - Advanced Linux System Management CLI"
    license: "MIT"
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/troncli/LICENSE
      - src: README.md
        dst: /usr/share/doc/troncli/README.md

release:
  draft: false
  prerelease: false
